const fs = require('fs-extra')
const path = require('path')
const tools = require('./tools')
const paths = require('./paths')

tools.removeEditStatus()
fs.removeSync(paths.srcDir)
fs.removeSync(paths.distDir)
fs.removeSync(paths.distTestDir)
fs.removeSync(paths.testDir)

fs.copySync(path.join(paths.templateDir, 'test'), paths.testDir)
fs.mkdirSync(paths.srcDir)
fs.createFileSync(path.join(paths.srcDir, '.gitkeep'))
fs.mkdirSync(paths.distDir)
fs.createFileSync(path.join(paths.distDir, '.gitkeep'))
fs.mkdirSync(paths.distTestDir)
fs.createFileSync(path.join(paths.distTestDir, '.gitkeep'))

console.log('Success !')